(() => {
  "use strict";
  const C = window.DRESSY_CONFIG;
  const canvas = document.querySelector("#artCanvas");
  const ctx = canvas.getContext("2d");
  const state = {
    panel: "clothes", character: C.characters[0], skin: C.characters[0].skin,
    hair: C.characters[0].hair, hairColor: C.characters[0].hairColor, clothes: C.clothes[0],
    stickers: [], strokes: [], brush: "paint", color: C.palettes[0], size: 12,
    backgroundImage: null, onlineBackgroundUrl: null, backgroundTransform:{x:0,y:0,scale:1}, drawing: false, selectedSticker: null, activeSticker: null, zoom: 1,
    stickerPaintMode: false, stickerPaintColor: "#ef476f", stickerPaintSize: 8, stickerDrawing: false,
    assetMode: true, assetCategory: "new-body", assetHues: {}, assetLayers: {
      "new-body":["base_body_a.png"],"face-eyes":["1.png"],"face-pupils":["1a.png"],
      "face-brows":["1.png"],"face-nose":["1.png"],"face-mouth":["1.png"],
      "casual-hair-back":["1b.webp"]
    }
  };
  const assetCache = new Map();
  const stickerImageCache = new Map();
  const stickerKeywords={"✨":"sparkles shine magic glitter","💖":"heart love pink","🌸":"flower blossom pink","⭐":"star yellow favorite","🎀":"bow ribbon cute","🌈":"rainbow colorful sky","🍓":"strawberry fruit red","🦋":"butterfly nature blue","👑":"crown royal princess queen","☁️":"cloud sky white","🌙":"moon night crescent","🧸":"teddy bear toy","🍒":"cherry fruit red","💎":"diamond gem jewel blue","🌼":"flower daisy yellow","⚡":"lightning bolt energy"};
  const assetOrder = ["casual-hair-back","body parts","new-body","bubble-body","snake-body","body decor","body-tints","body-spots","top underwear","casual-underwear","socks","shoes","casual-shoes","bottom","casual-bottom","top","casual-top","dress","casual-dress","jacket","casual-jacket","face-ears","face-eyes","face-pupils","face-lashes","face-brows","face-nose","face-mouth","face-decor","casual-hair-bangs","face items","accessories","casual-jewelry","hand_weapons","decor BG and front"];
  state.categoryOrder=[...assetOrder];
  let history = [], future = [], activeStroke = null, toastTimer, downloadUrl = null, downloadTimer;
  const $ = s => document.querySelector(s);

  function snapshot() {
    return JSON.stringify({ characterId: state.character.id, skin: state.skin, hair: state.hair, hairColor: state.hairColor, clothesId: state.clothes.id, stickers: state.stickers, strokes: state.strokes, assetMode:state.assetMode, assetLayers:state.assetLayers, assetHues:state.assetHues, categoryOrder:state.categoryOrder, onlineBackgroundUrl:state.onlineBackgroundUrl, backgroundTransform:state.backgroundTransform });
  }
  function commit() { history.push(snapshot()); if (history.length > 40) history.shift(); future = []; updateHistoryButtons(); }
  function restore(raw) {
    const s = JSON.parse(raw); state.character = C.characters.find(x => x.id === s.characterId) || C.characters[0];
    state.skin=s.skin; state.hair=s.hair; state.hairColor=s.hairColor; state.clothes=C.clothes.find(x=>x.id===s.clothesId)||C.clothes[0]; state.stickers=s.stickers; state.strokes=s.strokes; state.assetMode=!!s.assetMode;state.assetLayers=s.assetLayers||{};state.assetHues=s.assetHues||{};state.categoryOrder=s.categoryOrder||[...assetOrder];state.onlineBackgroundUrl=s.onlineBackgroundUrl||null;state.backgroundTransform=s.backgroundTransform||{x:0,y:0,scale:1};Object.keys(state.assetLayers).forEach(k=>{if(!Array.isArray(state.assetLayers[k]))state.assetLayers[k]=[state.assetLayers[k]]});state.activeSticker=null; render(); renderPanel();
  }
  function updateHistoryButtons(){ $("#undoBtn").disabled=!history.length; $("#redoBtn").disabled=!future.length; }
  function toast(msg){ const el=$("#toast"); el.textContent=msg; el.classList.add("show"); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove("show"),1800); }

  function roundRect(c,x,y,w,h,r,fill,stroke){ c.beginPath();c.roundRect(x,y,w,h,r); if(fill){c.fillStyle=fill;c.fill()} if(stroke){c.strokeStyle=stroke;c.stroke()} }
  function drawBackdrop(){
    const g=ctx.createLinearGradient(0,0,720,840);g.addColorStop(0,"#f7d9dd");g.addColorStop(.5,"#f5e9df");g.addColorStop(1,"#dce8e1");ctx.fillStyle=g;ctx.fillRect(0,0,720,840);
    ctx.globalAlpha=.35;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(80,100,130,0,7);ctx.fill();ctx.beginPath();ctx.arc(650,700,190,0,7);ctx.fill();ctx.globalAlpha=1;
    ctx.fillStyle="#ffffff99";ctx.beginPath();ctx.ellipse(360,773,190,30,0,0,7);ctx.fill();
  }
  function drawHair(back=true){
    const h=state.hair, col=state.hairColor;ctx.fillStyle=col;
    if(back){
      if(h==="waves"){roundRect(ctx,230,170,260,390,115,col); for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(245+i*58,490+(i%2)*20,55,0,7);ctx.fill()}}
      if(h==="bob") roundRect(ctx,239,175,242,300,105,col);
      if(h==="puffs"){ctx.beginPath();ctx.arc(235,240,85,0,7);ctx.arc(485,240,85,0,7);ctx.fill()}
      if(h==="ponytail"){ctx.beginPath();ctx.ellipse(498,285,75,190,-.22,0,7);ctx.fill();roundRect(ctx,245,175,225,260,100,col)}
      if(h==="short") roundRect(ctx,248,178,224,175,90,col);
      if(h==="buns"){ctx.beginPath();ctx.arc(260,170,70,0,7);ctx.arc(460,170,70,0,7);ctx.fill();roundRect(ctx,242,180,236,235,100,col)}
    } else {
      ctx.beginPath();ctx.arc(360,235,116,Math.PI,Math.PI*2);ctx.lineTo(463,264);ctx.quadraticCurveTo(420,218,360,210);ctx.quadraticCurveTo(315,230,250,285);ctx.closePath();ctx.fill();
      if(h==="short"){ctx.beginPath();ctx.moveTo(260,236);ctx.quadraticCurveTo(300,160,365,185);ctx.quadraticCurveTo(425,160,465,245);ctx.quadraticCurveTo(405,210,350,225);ctx.quadraticCurveTo(300,205,260,236);ctx.fill()}
    }
  }
  function drawBody(){
    const skin=state.skin;ctx.fillStyle=skin;roundRect(ctx,320,390,80,90,30,skin);ctx.beginPath();ctx.ellipse(360,300,108,132,0,0,7);ctx.fill();
    roundRect(ctx,232,450,62,245,31,skin);roundRect(ctx,426,450,62,245,31,skin);roundRect(ctx,299,635,57,145,28,skin);roundRect(ctx,364,635,57,145,28,skin);
    ctx.strokeStyle="#68484c";ctx.lineWidth=4;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(302,276);ctx.quadraticCurveTo(323,265,341,278);ctx.moveTo(379,278);ctx.quadraticCurveTo(397,265,418,276);ctx.stroke();
    ctx.fillStyle="#fffaf8";ctx.beginPath();ctx.ellipse(322,301,16,11,0,0,7);ctx.ellipse(398,301,16,11,0,0,7);ctx.fill();ctx.fillStyle="#4e3a3d";ctx.beginPath();ctx.ellipse(323,301,7,9,0,0,7);ctx.ellipse(397,301,7,9,0,0,7);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(326,298,2.2,0,7);ctx.arc(400,298,2.2,0,7);ctx.fill();
    ctx.strokeStyle="#c17b6f";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(360,305);ctx.quadraticCurveTo(350,327,362,328);ctx.stroke();ctx.fillStyle="#b8586e";ctx.beginPath();ctx.moveTo(336,349);ctx.quadraticCurveTo(360,337,384,349);ctx.quadraticCurveTo(360,371,336,349);ctx.fill();ctx.strokeStyle="#ffffff99";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(345,349);ctx.quadraticCurveTo(360,354,376,349);ctx.stroke();
    ctx.fillStyle="#ec9aa3";ctx.globalAlpha=.3;ctx.beginPath();ctx.ellipse(295,334,22,10,0,0,7);ctx.ellipse(425,334,22,10,0,0,7);ctx.fill();ctx.globalAlpha=1;
  }
  function drawClothes(){
    const o=state.clothes;ctx.fillStyle=o.color;
    ctx.beginPath();ctx.moveTo(315,423);ctx.quadraticCurveTo(360,450,405,423);ctx.lineTo(455,470);ctx.lineTo(420,620);ctx.lineTo(300,620);ctx.lineTo(265,470);ctx.closePath();ctx.fill();
    if(o.type==="dress"){ctx.beginPath();ctx.moveTo(305,585);ctx.lineTo(415,585);ctx.lineTo(468,710);ctx.lineTo(252,710);ctx.closePath();ctx.fill()}
    else {ctx.fillStyle="#4e5568";roundRect(ctx,295,605,62,105,12,"#4e5568");roundRect(ctx,363,605,62,105,12,"#4e5568")}
    if(o.type==="coat"){ctx.strokeStyle=o.accent;ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(360,452);ctx.lineTo(360,615);ctx.stroke()}
    ctx.fillStyle=o.accent;ctx.beginPath();ctx.arc(360,446,23,0,Math.PI);ctx.fill();
  }
  function assetPath(category,file){const cat=C.assetCategories.find(x=>x.id===category);const root=cat?.root||`assets/${category}`;return `${root.split("/").map(encodeURIComponent).join("/")}/${encodeURIComponent(file)}`}
  function requestAsset(category,file){const key=`${category}/${file}`;if(assetCache.has(key))return assetCache.get(key);const img=new Image();assetCache.set(key,img);img.onload=render;img.src=assetPath(category,file);return img}
  function prepareImage(img,url){if(/^https?:\/\//i.test(url)){img.crossOrigin="anonymous";img.referrerPolicy="no-referrer"}return img}
  function requestStickerImage(url){if(stickerImageCache.has(url))return stickerImageCache.get(url);const img=prepareImage(new Image(),url);stickerImageCache.set(url,img);img.onload=render;img.onerror=()=>{stickerImageCache.delete(url);toast("That image could not be loaded")};img.src=url;return img}
  function loadOnlineImage(url){return new Promise((resolve,reject)=>{const cached=stickerImageCache.get(url);if(cached?.complete&&cached.naturalWidth){resolve(cached);return}const img=cached||prepareImage(new Image(),url);stickerImageCache.set(url,img);img.onload=()=>{render();resolve(img)};img.onerror=()=>{stickerImageCache.delete(url);reject(new Error("Image failed to load"))};if(!cached)img.src=url})}
  function showBackgroundResults(box,pages){box.innerHTML="";const results=pages.map(p=>{const info=p.imageinfo?.[0];return info&&info.mime?.startsWith("image/")?{title:p.title,preview:info.thumburl||info.url,full:info.url}:null}).filter(Boolean);if(!results.length){box.innerHTML="<small>No backgrounds found. Try another search.</small>";return}results.forEach((result,i)=>{const button=document.createElement("button"),img=document.createElement("img");button.className="web-result";button.dataset.onlineBackground=result.preview;button.dataset.backgroundFallback=result.full;button.title=result.title;button.setAttribute("aria-label",`Use online background ${i+1}`);img.alt="";img.loading="eager";img.referrerPolicy="no-referrer";img.src=result.preview;img.onerror=()=>{if(result.full&&img.src!==result.full)img.src=result.full;else button.classList.add("image-load-failed")};button.append(img);box.append(button)})}
  function drawAssetLayers(){(state.categoryOrder||assetOrder).forEach(category=>{const files=state.assetLayers[category]||[];ctx.save();ctx.filter=`hue-rotate(${state.assetHues[category]||0}deg)`;(Array.isArray(files)?files:[files]).forEach(file=>{const img=requestAsset(category,file);if(img.complete&&img.naturalWidth){const scale=Math.min(720/img.naturalWidth,840/img.naturalHeight);const w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(720-w)/2,(840-h)/2,w,h)}});ctx.restore()})}
  function drawImageCover(img){const t=state.backgroundTransform||{x:0,y:0,scale:1},scale=Math.max(720/img.naturalWidth,840/img.naturalHeight)*t.scale,w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(720-w)/2+t.x,(840-h)/2+t.y,w,h)}
  function drawScene(){ drawBackdrop();if(state.onlineBackgroundUrl){const bg=requestStickerImage(state.onlineBackgroundUrl);if(bg.complete&&bg.naturalWidth){ctx.save();drawImageCover(bg);ctx.restore()}}if(state.backgroundImage){ctx.save();ctx.globalAlpha=.95;ctx.drawImage(state.backgroundImage,150,95,420,650);ctx.restore()} else if(state.assetMode){drawAssetLayers()} else {drawHair(true);drawBody();drawClothes();drawHair(false)} }
  function drawStrokes(){
    const layer=document.createElement("canvas");layer.width=720;layer.height=840;const pen=layer.getContext("2d");
    state.strokes.forEach(s=>{pen.save();pen.globalCompositeOperation=s.mode==="erase"?"destination-out":"source-over";pen.strokeStyle=s.color;pen.lineWidth=s.size;pen.lineCap="round";pen.lineJoin="round";pen.globalAlpha=s.mode==="makeup"?.38:1;pen.beginPath();s.points.forEach((p,i)=>i?pen.lineTo(p.x,p.y):pen.moveTo(p.x,p.y));pen.stroke();pen.restore()});
    ctx.drawImage(layer,0,0);
  }
  function stickerPoint(s,lx,ly){const sx=lx*(s.scaleX||1),sy=ly*(s.scaleY||1),skewedX=sx+(s.skewX||0)*sy,c=Math.cos(s.rotation||0),n=Math.sin(s.rotation||0);return{x:s.x+skewedX*c-sy*n,y:s.y+skewedX*n+sy*c}}
  function worldToSticker(s,p){const dx=p.x-s.x,dy=p.y-s.y,c=Math.cos(s.rotation||0),n=Math.sin(s.rotation||0),rx=dx*c+dy*n,ry=-dx*n+dy*c,sy=s.scaleY||1,sx=s.scaleX||1;return{x:(rx-(s.skewX||0)*ry)/sx,y:ry/sy}}
  function insideSticker(s,p){const q=worldToSticker(s,p),r=s.size*.62;return Math.abs(q.x)<=r&&Math.abs(q.y)<=r}
  function drawStickerPaint(s){if(!s.paintStrokes?.length)return;const r=s.size*.62;ctx.save();ctx.beginPath();ctx.rect(-r,-r,r*2,r*2);ctx.clip();s.paintStrokes.forEach(stroke=>{ctx.strokeStyle=stroke.color;ctx.lineWidth=stroke.size;ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();stroke.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(stroke.points.length===1)ctx.lineTo(stroke.points[0].x+.01,stroke.points[0].y+.01);ctx.stroke()});ctx.restore()}
  function stickerHandles(s){const r=s.size*.62;return{resize:stickerPoint(s,r,r),stretchX:stickerPoint(s,r,0),stretchY:stickerPoint(s,0,r),warp:stickerPoint(s,-r,0),rotate:stickerPoint(s,0,-r-34)}}
  function drawHandle(p,shape,color="#ef6e90"){ctx.save();ctx.fillStyle="#fff";ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();if(shape==="circle")ctx.arc(p.x,p.y,8,0,7);else{ctx.translate(p.x,p.y);if(shape==="diamond")ctx.rotate(Math.PI/4);ctx.rect(-7,-7,14,14)}ctx.fill();ctx.stroke();ctx.restore()}
  function drawStickers(){ state.stickers.forEach((s,i)=>{const sx=s.scaleX||1,sy=s.scaleY||1,sk=s.skewX||0,r=s.size*.62,opacity=s.opacity??1;ctx.save();ctx.globalAlpha=opacity;ctx.globalCompositeOperation="source-over";ctx.translate(s.x,s.y);ctx.rotate(s.rotation||0);ctx.transform(sx,0,sk*sy,sy,0,0);if(s.imageUrl){const img=requestStickerImage(s.imageUrl);if(img.complete&&img.naturalWidth)ctx.drawImage(img,-s.size/2,-s.size/2,s.size,s.size)}else{ctx.font=`${s.size}px "Segoe UI Emoji"`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(s.emoji,0,0);if(opacity>=1)ctx.fillText(s.emoji,0,0)}drawStickerPaint(s);ctx.restore();if(i===state.activeSticker){const corners=[stickerPoint(s,-r,-r),stickerPoint(s,r,-r),stickerPoint(s,r,r),stickerPoint(s,-r,r)],h=stickerHandles(s);ctx.save();ctx.setLineDash([7,5]);ctx.lineWidth=2;ctx.strokeStyle="#ef6e90";ctx.beginPath();corners.forEach((p,j)=>j?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(corners[0].x+(corners[1].x-corners[0].x)/2,corners[0].y+(corners[1].y-corners[0].y)/2);ctx.lineTo(h.rotate.x,h.rotate.y);ctx.stroke();ctx.restore();drawHandle(h.resize,"square");drawHandle(h.stretchX,"diamond","#6a9bd8");drawHandle(h.stretchY,"diamond","#6a9bd8");drawHandle(h.warp,"diamond","#8f6bc4");drawHandle(h.rotate,"circle","#407a63")}}) }
  function scheduleDownload(){clearTimeout(downloadTimer);const button=$("#downloadBtn");if(button){button.classList.add("preparing");button.setAttribute("aria-disabled","true");button.removeAttribute("download")}downloadTimer=setTimeout(()=>{try{canvas.toBlob(blob=>{if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=blob?URL.createObjectURL(blob):null;if(button&&downloadUrl){button.href=downloadUrl;button.download=`dressy-look-${Date.now()}.png`;button.classList.remove("preparing");button.setAttribute("aria-disabled","false")}},"image/png")}catch{downloadUrl=null}},100)}
  function render(){ctx.clearRect(0,0,720,840);drawScene();drawStrokes();drawStickers();scheduleDownload()}

  const panelTitles={character:"Choose a character",hair:"Style the hair",clothes:"Character wardrobe",body:"Choose the body",backgrounds:"Choose a background",stickers:"Add some sparkle",draw:"Brush & makeup"};
  function card(content, attrs, selected=""){return `<button class="choice-card ${selected?'selected':''}" ${attrs}>${content}</button>`}
  function renderPanel(){
    $("#panelTitle").textContent=panelTitles[state.panel];let html="";
    if(state.panel==="character"){
      html=`<div class="card-grid">${C.characters.map(x=>card(`<div class="character-preview"><div class="mini-avatar" style="background:${x.skin};--hair:${x.hairColor}"></div></div><strong>${x.name}</strong><em>${x.vibe}</em>`,`data-character="${x.id}"`,state.character.id===x.id)).join("")}</div>
      <span class="section-label">Search any person</span><form class="search-box" id="searchForm"><input id="searchInput" placeholder="Enter any person’s name" aria-label="Search for any person"><button>Search</button></form><p class="search-note">Ad-free public images from Wikimedia Commons. Results can be used as cartoon dress-up references.</p><div class="web-results" id="webResults"></div>`;
    } else if(state.panel==="hair"){
      html=`<span class="section-label">Hair style</span><div class="card-grid">${C.hair.map(x=>card(`<div class="style-icon">${x.icon}</div><strong>${x.name}</strong>`,`data-hair="${x.id}"`,state.hair===x.id)).join("")}</div><span class="section-label">Hair color</span><div class="swatches">${C.hairColors.map(x=>`<button class="swatch ${state.hairColor===x?'selected':''}" data-hair-color="${x}" style="background:${x}" aria-label="Hair color ${x}"></button>`).join("")}</div>`;
    } else if(state.panel==="clothes"){
      const cat=C.assetCategories.find(x=>x.id===state.assetCategory)||C.assetCategories[0];const selected=state.assetLayers[cat.id]||[];
      html=`<div class="wardrobe-layout"><div class="asset-tabs">${C.assetCategories.filter(x=>!x.hidden).map(x=>`<button class="asset-tab ${x.id===cat.id?'selected':''}" data-asset-category="${x.id}">${x.label}</button>`).join("")}</div><div class="wardrobe-content"><div class="asset-actions"><small>${cat.files.length} items · ${selected.length} selected</small>${selected.length?`<button class="remove-asset" data-remove-asset="${cat.id}">Clear category</button>`:""}</div><div class="category-controls"><label>Hue <output>${state.assetHues[cat.id]||0}°</output><input type="range" min="-180" max="180" value="${state.assetHues[cat.id]||0}" data-category-hue="${cat.id}"></label><div class="category-layer-buttons"><button data-category-layer="back" data-category-id="${cat.id}">↓ Move category back</button><button data-category-layer="forward" data-category-id="${cat.id}">↑ Move category forward</button></div></div><p class="asset-help">Select multiple items. They stack in the order you choose them.</p><div class="asset-grid">${cat.files.map((file,i)=>{const order=selected.indexOf(file);return `<button class="asset-card ${order>=0?'selected':''}" data-asset-file="${file}" data-asset-kind="${cat.id}" aria-label="Choose ${cat.label} ${i+1}">${order>=0?`<span class="selection-count">${order+1}</span>`:""}<img loading="lazy" src="${assetPath(cat.id,file)}" alt=""></button>`}).join("")}</div></div></div>`;
    } else if(state.panel==="body"){
      html=`<span class="section-label">Skin tone</span><div class="swatches">${C.skinTones.map(x=>`<button class="swatch ${state.skin===x?'selected':''}" data-skin="${x}" style="background:${x}" aria-label="Skin tone ${x}"></button>`).join("")} </div><p class="search-note" style="margin-top:18px">Every character can wear every hairstyle and outfit. Choose any tone that feels right for your creation.</p>`;
    } else if(state.panel==="backgrounds"){
      const cat=C.assetCategories.find(x=>x.id==="background-library"),t=state.backgroundTransform||{x:0,y:0,scale:1};
      html=`<a class="background-credit" href="https://potat0master.itch.io/free-visual-novel-backgrounds-mansion-pack" target="_blank" rel="noopener noreferrer">Mansion backgrounds by Potat0Master on itch.io ↗</a><form class="sticker-search" id="backgroundSearchForm"><span>⌕</span><input id="backgroundSearch" type="search" placeholder="Search forests, rooms, beaches…" aria-label="Search online backgrounds"><button>Search online</button></form><div class="background-actions">${state.onlineBackgroundUrl?'<button data-clear-online-background>Remove background</button>':''}<button data-reset-background>Reset position</button></div><p class="search-note">Ad-free public images from Wikimedia Commons. Check the image license before sharing.</p><div class="web-results background-results" id="backgroundResults"></div>${state.onlineBackgroundUrl?`<div class="background-transform"><label>Scale <output>${Math.round(t.scale*100)}%</output><input type="range" min="50" max="250" value="${Math.round(t.scale*100)}" data-background-transform="scale"></label><label>Move left / right <output>${t.x}</output><input type="range" min="-360" max="360" value="${t.x}" data-background-transform="x"></label><label>Move up / down <output>${t.y}</output><input type="range" min="-420" max="420" value="${t.y}" data-background-transform="y"></label></div>`:""}<span class="section-label">Mansion backgrounds</span><div class="asset-grid background-library">${cat.files.map((file,i)=>{const src=assetPath(cat.id,file),selected=state.onlineBackgroundUrl===src;return `<button class="asset-card ${selected?'selected':''}" data-built-in-background="${src}" aria-label="Choose mansion background ${i+1}"><img loading="lazy" src="${src}" alt=""></button>`}).join("")}</div><a class="background-credit bottom" href="https://potat0master.itch.io/free-visual-novel-backgrounds-mansion-pack" target="_blank" rel="noopener noreferrer">Background pack by Potat0Master ↗</a>`;
    } else if(state.panel==="stickers"){
      const active=state.activeSticker!==null?state.stickers[state.activeSticker]:null;
      html=`<form class="sticker-search" id="stickerSearchForm"><span>⌕</span><input id="stickerSearch" type="search" placeholder="Search hearts, flowers, cats…" aria-label="Search stickers"><button>Search online</button></form><div class="sticker-grid">${C.stickers.map(x=>`<button class="sticker-btn" data-sticker="${x}" data-search="${stickerKeywords[x]||''}" aria-label="Add ${x}">${x}</button>`).join("")}</div><div class="online-sticker-results" id="onlineStickerResults"></div><span class="section-label">Selected sticker</span><div class="brush-types"><button class="brush-btn" data-resize="smaller">− Smaller</button><button class="brush-btn" data-resize="larger">＋ Larger</button><button class="brush-btn ${state.stickerPaintMode?'selected':''}" data-sticker-paint="toggle">✎ Paint sticker</button></div><div class="sticker-layer-row"><button data-sticker-layer="down">↓ Send backward</button><button data-sticker-layer="up">↑ Bring forward</button></div><span class="section-label">Sticker paint</span><div class="swatches">${C.palettes.map(x=>`<button class="swatch ${state.stickerPaintColor===x?'selected':''}" data-sticker-paint-color="${x}" style="background:${x}" aria-label="Sticker paint color ${x}"></button>`).join("")}</div><div class="range-row"><span>•</span><input id="stickerPaintSize" type="range" min="2" max="35" value="${state.stickerPaintSize}"><span>●</span></div><button class="clear-btn" data-clear-sticker-paint>Clear sticker paint</button><span class="section-label">Transparency</span><div class="range-row"><span>0%</span><input id="stickerOpacity" type="range" min="5" max="100" value="${Math.round((active?.opacity??1)*100)}" ${active?'':'disabled'}><span>100%</span></div><p class="search-note">Paint mode changes only the selected sticker. Online results come from Wikimedia Commons.</p>`;
    } else {
      html=`<span class="section-label">Brush type</span><div class="brush-types"><button class="brush-btn ${state.brush==='paint'?'selected':''}" data-brush="paint">Paint</button><button class="brush-btn ${state.brush==='makeup'?'selected':''}" data-brush="makeup">Makeup</button><button class="brush-btn ${state.brush==='erase'?'selected':''}" data-brush="erase">Eraser</button></div><span class="section-label">Color</span><div class="swatches">${C.palettes.map(x=>`<button class="swatch ${state.color===x?'selected':''}" data-color="${x}" style="background:${x}"></button>`).join("")}</div><span class="section-label">Brush size</span><div class="range-row"><span>•</span><input id="sizeRange" type="range" min="3" max="55" value="${state.size}"><span>●</span></div><button class="clear-btn" id="clearArt">Clear drawings</button>`;
    }
    $("#panelContent").innerHTML=html;
  }
  function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*840/r.height}}
  function findSticker(p){for(let i=state.stickers.length-1;i>=0;i--){const s=state.stickers[i],reach=s.size*.8*Math.max(Math.abs(s.scaleX||1),Math.abs(s.scaleY||1));if(Math.hypot(p.x-s.x,p.y-s.y)<reach)return i}return -1}
  function findStickerHandle(p){if(state.activeSticker===null)return null;const s=state.stickers[state.activeSticker];if(!s)return null;const h=stickerHandles(s);for(const [mode,hp] of Object.entries(h))if(Math.hypot(p.x-hp.x,p.y-hp.y)<16)return mode;return null}
  canvas.addEventListener("pointerdown",e=>{const p=point(e),handle=findStickerHandle(p);canvas.setPointerCapture(e.pointerId);if(handle){commit();const s=state.stickers[state.activeSticker];state.transformMode=handle;state.transformStart={p,rotation:s.rotation||0,scaleX:s.scaleX||1,scaleY:s.scaleY||1,skewX:s.skewX||0,distance:Math.max(1,Math.hypot(p.x-s.x,p.y-s.y)),angle:Math.atan2(p.y-s.y,p.x-s.x)};return}const active=state.stickers[state.activeSticker];if(state.stickerPaintMode&&active&&insideSticker(active,p)){commit();state.stickerDrawing=true;state.activeStickerPaintStroke={color:state.stickerPaintColor,size:state.stickerPaintSize,points:[worldToSticker(active,p)]};(active.paintStrokes||(active.paintStrokes=[])).push(state.activeStickerPaintStroke);render();return}const hit=findSticker(p);if(hit>=0){commit();state.selectedSticker=hit;state.activeSticker=hit;state.dragOffset={x:p.x-state.stickers[hit].x,y:p.y-state.stickers[hit].y};render();return}state.activeSticker=null;if(state.panel!=="draw"){render();return}commit();state.drawing=true;activeStroke={mode:state.brush,color:state.color,size:state.size,points:[p]};state.strokes.push(activeStroke)});
  canvas.addEventListener("pointermove",e=>{const p=point(e);if(state.stickerDrawing){const s=state.stickers[state.activeSticker];if(s&&state.activeStickerPaintStroke){state.activeStickerPaintStroke.points.push(worldToSticker(s,p));render()}}else if(state.transformMode){const s=state.stickers[state.activeSticker],a=state.transformStart,c=Math.cos(-(s.rotation||0)),n=Math.sin(-(s.rotation||0)),dx=p.x-s.x,dy=p.y-s.y,localX=dx*c-dy*n,localY=dx*n+dy*c;if(state.transformMode==="rotate")s.rotation=a.rotation+Math.atan2(p.y-s.y,p.x-s.x)-a.angle;if(state.transformMode==="resize"){const ratio=Math.max(.2,Math.min(5,Math.hypot(dx,dy)/a.distance));s.scaleX=a.scaleX*ratio;s.scaleY=a.scaleY*ratio}if(state.transformMode==="stretchX")s.scaleX=Math.max(.2,Math.min(5,Math.abs(localX)/(s.size*.62)));if(state.transformMode==="stretchY")s.scaleY=Math.max(.2,Math.min(5,Math.abs(localY)/(s.size*.62)));if(state.transformMode==="warp")s.skewX=Math.max(-1.5,Math.min(1.5,a.skewX+(a.p.x-p.x)/120));render()}else if(state.selectedSticker!==null){const s=state.stickers[state.selectedSticker];s.x=p.x-state.dragOffset.x;s.y=p.y-state.dragOffset.y;render()}else if(state.drawing){activeStroke.points.push(p);render()}});
  const endPointer=()=>{state.drawing=false;state.stickerDrawing=false;state.activeStickerPaintStroke=null;activeStroke=null;state.selectedSticker=null;state.transformMode=null;state.transformStart=null;if(state.panel==="stickers")renderPanel()};canvas.addEventListener("pointerup",endPointer);canvas.addEventListener("pointercancel",endPointer);
  canvas.addEventListener("dblclick",e=>{const i=findSticker(point(e));if(i>=0){commit();state.stickers.splice(i,1);state.activeSticker=null;render();if(state.panel==="stickers")renderPanel();toast("Sticker removed")}});
  function addSticker(emoji){commit();state.stickers.push({emoji,x:360+(Math.random()-.5)*100,y:360+(Math.random()-.5)*120,size:62,rotation:(Math.random()-.5)*.3,scaleX:1,scaleY:1,skewX:0,opacity:1});state.activeSticker=state.stickers.length-1;render();renderPanel();toast(`${emoji} added — use its handles to transform it`)}
  function addImageSticker(url){commit();requestStickerImage(url);state.stickers.push({imageUrl:url,x:360+(Math.random()-.5)*100,y:360+(Math.random()-.5)*120,size:100,rotation:0,scaleX:1,scaleY:1,skewX:0,opacity:1});state.activeSticker=state.stickers.length-1;render();renderPanel();toast("Online sticker added")}
  function layerList(kind){const current=state.assetLayers[kind];return state.assetLayers[kind]=Array.isArray(current)?current:(current?[current]:[])}
  function randomizeLook(){
    commit();state.backgroundImage=null;state.assetMode=true;state.assetLayers={};
    const bodyIds=["new-body","bubble-body","snake-body"],bodyCat=C.assetCategories.find(cat=>cat.id===bodyIds[Math.floor(Math.random()*bodyIds.length)]),bodyFile=bodyCat.files[Math.floor(Math.random()*bodyCat.files.length)];state.assetLayers[bodyCat.id]=[bodyFile];requestAsset(bodyCat.id,bodyFile);
    const hairIds=["casual-hair-back","casual-hair-bangs"];hairIds.forEach(id=>{const cat=C.assetCategories.find(x=>x.id===id),file=cat.files[Math.floor(Math.random()*cat.files.length)];state.assetLayers[id]=[file];requestAsset(id,file)});
    C.assetCategories.filter(cat=>cat.root&&!cat.hidden&&!cat.root.startsWith("assets/")&&!bodyIds.includes(cat.id)&&!hairIds.includes(cat.id)).forEach(cat=>{
      const count=Math.min(cat.files.length,Math.random()<.45?2:1),pool=[...cat.files],chosen=[];
      while(chosen.length<count){chosen.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0])}
      state.assetLayers[cat.id]=chosen;chosen.forEach(file=>requestAsset(cat.id,file));
    });render();renderPanel();toast("A new random look appeared!")
  }
  document.addEventListener("click",e=>{
    const b=e.target.closest("button");if(!b)return;
    if(b.dataset.panel){state.panel=b.dataset.panel;if(b.dataset.panel==="body"){state.panel="clothes";state.assetCategory="new-body"}if(b.dataset.panel==="hair"){state.panel="clothes";state.assetCategory="casual-hair-back"}document.querySelectorAll(".rail-btn").forEach(x=>x.classList.toggle("active",x===b));renderPanel()}
    if(b.dataset.character){commit();state.character=C.characters.find(x=>x.id===b.dataset.character);state.skin=state.character.skin;state.hair=state.character.hair;state.hairColor=state.character.hairColor;state.backgroundImage=null;state.assetMode=false;render();renderPanel()}
    if(b.dataset.hair){commit();state.hair=b.dataset.hair;render();renderPanel()} if(b.dataset.hairColor){commit();state.hairColor=b.dataset.hairColor;render();renderPanel()}
    if(b.dataset.clothes){commit();state.clothes=C.clothes.find(x=>x.id===b.dataset.clothes);state.assetMode=false;render();renderPanel()} if(b.dataset.skin){commit();state.skin=b.dataset.skin;render();renderPanel()}
    if(b.dataset.assetCategory){state.assetCategory=b.dataset.assetCategory;renderPanel()}if(b.dataset.assetFile){commit();state.assetMode=true;state.backgroundImage=null;const list=layerList(b.dataset.assetKind),at=list.indexOf(b.dataset.assetFile);if(at>=0){list.splice(at,1);toast("Layer removed")}else{list.push(b.dataset.assetFile);requestAsset(b.dataset.assetKind,b.dataset.assetFile);toast("Layer added")}render();renderPanel()}
    if(b.dataset.removeAsset){commit();delete state.assetLayers[b.dataset.removeAsset];render();renderPanel();toast("Layer removed")}
    if(b.dataset.sticker)addSticker(b.dataset.sticker);if(b.dataset.quick)addSticker(b.dataset.quick);if(b.dataset.resize){if(state.activeSticker===null||!state.stickers[state.activeSticker]){toast("Select a sticker on the canvas first");return}commit();const s=state.stickers[state.activeSticker];s.size=Math.max(24,Math.min(180,s.size+(b.dataset.resize==="larger"?14:-14)));render()}if(b.dataset.stickerLayer){if(state.activeSticker===null){toast("Select a sticker first");return}const from=state.activeSticker,to=b.dataset.stickerLayer==="up"?Math.min(state.stickers.length-1,from+1):Math.max(0,from-1);if(from===to){toast(b.dataset.stickerLayer==="up"?"Already on top":"Already at the bottom");return}commit();const moved=state.stickers.splice(from,1)[0];state.stickers.splice(to,0,moved);state.activeSticker=to;render();toast(b.dataset.stickerLayer==="up"?"Sticker moved forward":"Sticker moved backward")}if(b.dataset.brush){state.brush=b.dataset.brush;renderPanel()}if(b.dataset.color){state.color=b.dataset.color;renderPanel()}
  });
  document.addEventListener("click",e=>{
    const b=e.target.closest("button");if(!b)return;
    if(b.dataset.stickerPaint==="toggle"){if(state.activeSticker===null){toast("Select a sticker first");return}state.stickerPaintMode=!state.stickerPaintMode;renderPanel();toast(state.stickerPaintMode?"Draw directly on the selected sticker":"Sticker paint mode off")}
    if(b.dataset.stickerPaintColor){state.stickerPaintColor=b.dataset.stickerPaintColor;renderPanel()}
    if(b.hasAttribute("data-clear-sticker-paint")){const s=state.stickers[state.activeSticker];if(!s){toast("Select a sticker first");return}commit();s.paintStrokes=[];render();toast("Sticker paint cleared")}
    if(b.hasAttribute("data-clear-online-background")){commit();state.onlineBackgroundUrl=null;state.backgroundTransform={x:0,y:0,scale:1};render();renderPanel();toast("Background removed")}
    if(b.hasAttribute("data-reset-background")){commit();state.backgroundTransform={x:0,y:0,scale:1};render();renderPanel();toast("Background position reset")}
  });
  document.addEventListener("click",e=>{
    const b=e.target.closest("[data-category-layer]");if(!b)return;const id=b.dataset.categoryId,order=state.categoryOrder,index=order.indexOf(id),step=b.dataset.categoryLayer==="forward"?1:-1,next=Math.max(0,Math.min(order.length-1,index+step));if(index<0||index===next){toast(step>0?"Category is already at the front":"Category is already at the back");return}commit();order.splice(index,1);order.splice(next,0,id);render();toast(step>0?"Category moved forward":"Category moved back")
  });
  $("#panelContent").addEventListener("input",e=>{if(e.target.id==="stickerPaintSize")state.stickerPaintSize=+e.target.value});
  $("#panelContent").addEventListener("pointerdown",e=>{if(e.target.dataset.backgroundTransform)commit()});
  $("#panelContent").addEventListener("input",e=>{const key=e.target.dataset.backgroundTransform;if(!key)return;state.backgroundTransform[key]=key==="scale"?+e.target.value/100:+e.target.value;const output=e.target.closest("label")?.querySelector("output");if(output)output.textContent=key==="scale"?`${e.target.value}%`:e.target.value;render()});
  $("#panelContent").addEventListener("pointerdown",e=>{if(e.target.dataset.categoryHue)commit()});
  $("#panelContent").addEventListener("input",e=>{const id=e.target.dataset.categoryHue;if(!id)return;state.assetHues[id]=+e.target.value;const output=e.target.closest("label")?.querySelector("output");if(output)output.textContent=`${e.target.value}°`;render()});
  $("#panelContent").addEventListener("pointerdown",e=>{if(e.target.id==="stickerOpacity"&&state.activeSticker!==null)commit()});
  $("#panelContent").addEventListener("input",e=>{if(e.target.id==="sizeRange")state.size=+e.target.value;if(e.target.id==="stickerOpacity"&&state.activeSticker!==null){state.stickers[state.activeSticker].opacity=+e.target.value/100;render()}if(e.target.id==="stickerSearch"){const q=e.target.value.trim().toLowerCase();document.querySelectorAll(".sticker-btn").forEach(btn=>btn.hidden=!!q&&!`${btn.dataset.search} ${btn.textContent}`.toLowerCase().includes(q))}});
  $("#panelContent").addEventListener("click",e=>{if(e.target.closest("#clearArt")){commit();state.strokes=[];render();toast("Drawings cleared")}});
  $("#panelContent").addEventListener("submit",async e=>{
    if(e.target.id==="backgroundSearchForm"){e.preventDefault();const q=$("#backgroundSearch").value.trim(),box=$("#backgroundResults");if(!q)return;box.innerHTML="<small>Searching Wikimedia Commons…</small>";try{const url=`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q+" background photograph filetype:bitmap")}&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url%7Cmime&iiurlwidth=720&origin=*&format=json&formatversion=2`,response=await fetch(url);if(!response.ok)throw new Error(`Search failed: ${response.status}`);const data=await response.json(),pages=data.query?.pages||[];showBackgroundResults(box,pages)}catch{box.innerHTML="<small>Online background search is unavailable right now. Please try again.</small>"}return}
    if(e.target.id==="stickerSearchForm"){e.preventDefault();const q=$("#stickerSearch").value.trim(),box=$("#onlineStickerResults");if(!q)return;box.innerHTML="<small>Searching Wikimedia Commons…</small>";try{const url=`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q+" sticker transparent png")}&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url&iiurlwidth=240&origin=*&format=json`,data=await fetch(url).then(r=>r.json()),pages=Object.values(data.query?.pages||{});box.innerHTML=pages.map((p,i)=>{const info=p.imageinfo?.[0],src=info?.thumburl||info?.url;return src?`<button class="online-sticker" data-online-sticker="${src}" title="${p.title.replace(/"/g,'&quot;')}" aria-label="Add online sticker ${i+1}"><img src="${src}" alt=""></button>`:""}).join("")||"<small>No online stickers found. Try another search.</small>"}catch{box.innerHTML="<small>Online sticker search is unavailable right now.</small>"}return}
    if(e.target.id!=="searchForm")return;e.preventDefault();const q=$("#searchInput").value.trim();if(!q)return;const box=$("#webResults");box.innerHTML="<small>Searching…</small>";
    try{const url=`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q+" portrait filetype:bitmap")}&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url&iiurlwidth=300&origin=*&format=json`;const data=await fetch(url).then(r=>r.json());const pages=Object.values(data.query?.pages||{});box.innerHTML=pages.map((p,i)=>`<button class="web-result" data-web="${i}" data-url="${p.imageinfo?.[0]?.thumburl||p.imageinfo?.[0]?.url}" title="${p.title.replace(/"/g,'&quot;')}"><img src="${p.imageinfo?.[0]?.thumburl}" alt="${p.title.replace(/"/g,'&quot;')}"></button>`).join("")||"<small>No portrait found. Try the person’s full name.</small>"}catch{box.innerHTML="<small>Search is unavailable. Built-in characters still work offline.</small>"}
  });
  $("#panelContent").addEventListener("click",e=>{const b=e.target.closest("[data-online-sticker]");if(b)addImageSticker(b.dataset.onlineSticker)});
  $("#panelContent").addEventListener("click",async e=>{const b=e.target.closest("[data-online-background]");if(!b)return;b.disabled=true;const choices=[b.dataset.onlineBackground,b.dataset.backgroundFallback].filter((url,i,list)=>url&&list.indexOf(url)===i);for(const url of choices){try{await loadOnlineImage(url);commit();state.onlineBackgroundUrl=url;render();renderPanel();toast("Online background added");return}catch{}}b.disabled=false;toast("That background could not be loaded. Try another image.")});
  $("#panelContent").addEventListener("click",async e=>{const b=e.target.closest("[data-built-in-background]");if(!b)return;b.disabled=true;try{await loadOnlineImage(b.dataset.builtInBackground);commit();state.onlineBackgroundUrl=b.dataset.builtInBackground;state.backgroundTransform={x:0,y:0,scale:1};render();renderPanel();toast("Mansion background added")}catch{b.disabled=false;toast("That background could not be loaded")}});
  $("#panelContent").addEventListener("click",e=>{const b=e.target.closest("[data-web]");if(!b)return;const img=new Image();img.crossOrigin="anonymous";img.onload=()=>{commit();state.backgroundImage=img;render();toast("Web character added")};img.onerror=()=>toast("That image could not be loaded");img.src=b.dataset.url});
  $("#undoBtn").onclick=()=>{if(!history.length)return;future.push(snapshot());restore(history.pop());updateHistoryButtons()};$("#redoBtn").onclick=()=>{if(!future.length)return;history.push(snapshot());restore(future.pop());updateHistoryButtons()};
  $("#collapseBtn").onclick=()=>{$(".app-shell").classList.toggle("collapsed");$("#collapseBtn").textContent=$(".app-shell").classList.contains("collapsed")?"›":"‹"};
  $("#reopenPanel").onclick=()=>{$(".app-shell").classList.remove("collapsed");$("#collapseBtn").textContent="‹"};
  $("#zoomIn").onclick=()=>setZoom(Math.min(1.3,state.zoom+.1));$("#zoomOut").onclick=()=>setZoom(Math.max(.7,state.zoom-.1));function setZoom(z){state.zoom=Math.round(z*10)/10;canvas.style.transform=`scale(${state.zoom})`;$("#zoomLabel").textContent=`${Math.round(state.zoom*100)}%`}
  $("#randomizeBtn").onclick=randomizeLook;
  $("#downloadBtn").onclick=e=>{if(!downloadUrl){e.preventDefault();toast("Preparing your image — try again in a moment");scheduleDownload();return}toast("Your look was saved!")};
  renderPanel();render();updateHistoryButtons();
})();
